language: node_js
node_js:
- '0.10'
before_install:
  - npm install npm -g
deploy:
  - provider: npm
    skip_cleanup: true
    clean_up: false
    email: replace-me
    api_key:
      secure: replace-me
    on:
      tags: true
      all_branches: true
