sudo: false
language: node_js
cache:
  bundler: true
  directories:
    - node_modules
notifications:
  flowdock: e7454f5285e7b9ab67009802d5560490
node_js:
- '0.10'
deploy:
  provider: npm
  skip_cleanup: true
  clean_up: false
  email: serveradmin@octoblu.com
  api_key:
    secure: F4PEfHxk21BFAuwXuYU1+ppDjZTzTTGhGwzY1JLMskoXsG9t1nD4mpfAjZV/McplJeWo3Uk8nnLsiPSUFM1E1I6F3hVN0MG587jfjfBnOCkdpTYjwsT7GmoZs4fNNyXZ2NsN/ROEhb6rVLY2dIQucsKsEBxFq65b5h0lB6pKXbI=
  on:
    tags: true
    all_branches: true